/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ruin_psp_PSP */

#ifndef _Included_com_ruin_psp_PSP
#define _Included_com_ruin_psp_PSP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ruin_psp_PSP
 * Method:    greetSelf
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ruin_psp_PSP_greetSelf
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
